on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  asd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo random branch
